name: Metrics

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          user: SEIM-CHAN
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Tokyo

      - name: Commit and push metrics
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update github metrics"
          file_pattern: github-metrics.svg
